name: Webapp build and deploy
run-name: Building and deploying webapp to github pages
on:
  push:
    paths:
      - 'webapp/**'
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: actions/checkout@v4
      - run: yarn build
        working-directory: webapp/
      - uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: webapp/build/**
          overwrite: true
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: webapp
